# Generated by Django 5.0.2 on 2024-02-17 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=320)),
                ('number_of_copies', models.IntegerField()),
            ],
        ),
    ]
