# Generated by Django 5.0.2 on 2024-02-17 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('circulation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='circulation',
            name='returned_on',
            field=models.DateTimeField(null=True),
        ),
    ]
