# Generated by Django 5.0.2 on 2024-02-17 08:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('circulation', '0002_alter_circulation_returned_on'),
    ]

    operations = [
        migrations.RenameField(
            model_name='circulation',
            old_name='cirulated_on',
            new_name='circulated_on',
        ),
    ]
