# Generated by Django 5.0.2 on 2024-02-17 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('circulation', '0003_rename_cirulated_on_circulation_circulated_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='circulation',
            name='circulated_on',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='circulation',
            name='returned_on',
            field=models.DateTimeField(db_index=True, null=True),
        ),
    ]
